rabbit:
  host: $env:RABBITMQ_HOST
  port: $env:RABBITMQ_PORT
  user: $env:RABBITMQ_USER
  password: $env:RABBITMQ_PASSWORD

logger:
  level: "ERROR"

storage:
#  storageType: memory
  storageType: sql
  database:
    host: $env:POSTGRES_HOST
    port: $env:POSTGRES_PORT
    database: $env:POSTGRES_DB
    username: $env:POSTGRES_USERNAME
    password: $env:POSTGRES_PASSWORD
