rabbit:
  host: 127.0.0.1
  port: 5672
  user: user
  password: pass

logger:
  level: "DEBUG"

storage:
#  storageType: memory
  storageType: sql
  database:
    host: 127.0.0.1
    port: 5532
    database: postgres
    username: postgres
    password: pas
